import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      buttonShadow: {
        color: "#00000040",
        type: "dropShadow",
        x: 0,
        y: 2,
        blur: 12,
        spread: 0,
      },
      fontFamilies: {
        inter: "Inter",
      },
      lineHeights: {
        0: "AUTO",
        1: "140%",
        2: "28",
        3: "16",
      },
      fontWeights: {
        inter_0: "Bold",
        inter_1: "Medium",
        inter_2: "Regular",
      },
      fontSize: {
        0: "12",
        1: "14",
        2: "16",
        3: "18",
        4: "20",
        5: "24",
        6: "28",
        7: "32",
        8: "60",
        9: "80",
      },
      letterSpacing: {
        0: "1.5%",
        1: "0%",
        2: "-1%",
      },
      paragraphSpacing: {
        0: "0",
      },
      title: {
        "80px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "AUTO",
            fontSize: "80",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "AUTO",
            fontSize: "80",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "AUTO",
            fontSize: "80",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
        "60px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "60",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "60",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "AUTO",
            fontSize: "60",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
        "32px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "32",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "32",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "140%",
            fontSize: "32",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
        "28px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "28",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "28",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "AUTO",
            fontSize: "28",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
        "20px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "20",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "20",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "AUTO",
            fontSize: "20",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      subTitle: {
        "24px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "24",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "24",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "AUTO",
            fontSize: "24",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
        "18px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "18",
            letterSpacing: "0%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "18",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "28",
            fontSize: "18",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      caption: {
        "12px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "28",
            fontSize: "12",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "12",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "140%",
            fontSize: "12",
            letterSpacing: "1.5%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      label1: {
        "16px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "16",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      label2: {
        "14px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "14",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "14",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "140%",
            fontSize: "14",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      body: {
        "16px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "16",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      bodyCaption: {
        "14px": {
          bold: {
            fontFamily: "Inter",
            fontWeight: "Bold",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          medium: {
            fontFamily: "Inter",
            fontWeight: "Medium",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
          regular: {
            fontFamily: "Inter",
            fontWeight: "Regular",
            lineHeight: "140%",
            fontSize: "16",
            letterSpacing: "-1%",
            paragraphSpacing: "0",
            paragraphIndent: "0px",
            textCase: "none",
            textDecoration: "none",
          },
        },
      },
      textCase: {
        none: "none",
      },
      textDecoration: {
        none: "none",
      },
      paragraphIndent: {
        0: "0px",
      },
    },
  },
};
export default config;
